services:
  # cloudflaretunnel:
  #  container_name: cloudflare
  # image: cloudflare/cloudflared:latest
  #  restart: unless-stopped
  #  environment: 
  #   - TUNNEL_TOKEN=$TUNNEL_TOKEN
  #  command: tunnel --no-autoupdate run
  #  network_mode: host

  cloudflare-ddns:
    image: timothyjmiller/cloudflare-ddns:latest
    container_name: cloudflare-ddns
    security_opt:
      - no-new-privileges:true
    network_mode: "host"
    environment:
      - PUID=1000
      - PGID=1000
    volumes:
      - /docker/appdata/cloudflare/ddns/config.json:/config.json
    restart: unless-stopped


